String to postfix tests
Honny1/ivs_calc pull request #28
Opened 2021-04-12 22:07 UTC by MKlofera

2021-04-12 22:07 UTC, pep8speaks commented
Hello @MKlofera! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`src/duck_calc/infixToPostfix.py`](https://github.com/Honny1/ivs_calc/blob/434fb9a252da7ce20733dbb242c6f10af25605ce/src/duck_calc/infixToPostfix.py):

> [Line 48:19](https://github.com/Honny1/ivs_calc/blob/434fb9a252da7ce20733dbb242c6f10af25605ce/src/duck_calc/infixToPostfix.py#L48): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`src/tests/string_to_posftix_tests.py`](https://github.com/Honny1/ivs_calc/blob/434fb9a252da7ce20733dbb242c6f10af25605ce/src/tests/string_to_posftix_tests.py):

> [Line 63:1](https://github.com/Honny1/ivs_calc/blob/434fb9a252da7ce20733dbb242c6f10af25605ce/src/tests/string_to_posftix_tests.py#L63): [E304](https://duckduckgo.com/?q=pep8%20E304) blank lines found after function decorator
> [Line 93:1](https://github.com/Honny1/ivs_calc/blob/434fb9a252da7ce20733dbb242c6f10af25605ce/src/tests/string_to_posftix_tests.py#L93): [E304](https://duckduckgo.com/?q=pep8%20E304) blank lines found after function decorator
> [Line 95:39](https://github.com/Honny1/ivs_calc/blob/434fb9a252da7ce20733dbb242c6f10af25605ce/src/tests/string_to_posftix_tests.py#L95): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2021-04-13 12:10 UTC, TheRealTom requested changes
Ještě to chce změny a budeš muset dopsat ještě jednu funkci do mathlib (konkrétně už v jednotlivých komentářích u řádků).

2021-04-13 12:10 UTC, TheRealTom commented on src/tests/string_to_posftix_tests.py
> +    assert result_of_mathlib is None3"
Přidat na konec prázdný řádek.

2021-04-13 12:10 UTC, TheRealTom commented on src/tests/string_to_posftix_tests.py
> +    assert result_of_mathlib is None3"
Poslední řádek není úplně správně, změň to None3 na None, změň tu funkci solve_mathematic_problem a odstraň tu uvozovku.

2021-04-13 12:10 UTC, TheRealTom commented on src/tests/string_to_posftix_tests.py
> +    assert MathLib.solve_mathematic_problem(problem) == result
solve_mathematic_problem vrací už výsledek funkce. Mělo by se použít třeba "transofrm_string_to_postfix", etc.

2021-04-13 13:18 UTC, Honny1 requested changes
Je potřeba odstranit předchozí commit. Nemá tam co dělat. Pomoci `git rebasese` to dá fixnout.

2021-04-14 21:35 UTC, Honny1 requested changes
To to nebude fungovat. Myslím že by to mělo vypadat takto: 
```assert MathLib.transform_string_to_postfix(problem) is None```

2021-04-14 21:36 UTC, Honny1 requested changes

2021-04-14 21:36 UTC, Honny1 commented on src/tests/test_string_to_postfix_convertion.py
> +    result_of_mathlib = transform_string_to_postfix(problem)
To to nebude fungovat. Myslím že by to mělo vypadat takto: 
```assert MathLib.transform_string_to_postfix(problem) is None```

2021-04-16 11:01 UTC, merged