[IN TESTING] Vytvaři Makefile
Honny1/ivs_calc pull request #44
Opened 2021-04-21 22:14 UTC by Honny1

2021-04-21 23:26 UTC, smn22 approved these changes
ok

2021-04-22 17:30 UTC, TheRealTom requested changes
Opravit pravopis a jednotné psaní bez háčků a čárek v komentářích. Možná bys všechny komenty mohl přepsat i do angličtiny, ale to je už na tobě 🦄

2021-04-22 17:30 UTC, TheRealTom commented on src/Makefile
> +# Nainstaluje aplikaci primo se zdrojovich kódu
```suggestion
# Nainstaluje aplikaci primo ze zdrojovych kodu
```

2021-04-22 17:30 UTC, TheRealTom commented on src/Makefile
> +# Vytvori deb balicek ve složce installer
```suggestion
# Vytvori deb balicek ve slozce installer
```

2021-04-22 17:51 UTC, merged